### ISSUE TITLE
可充电电池MS621和电路的请教

### ISSUE THREAD

**Issue by tonyho** [kekemuyu/linewatch#1]
你好，我看到你的LineWatch使用的RTC Battery是MS621，是3.3V经过一个二极管给电池供电，请问一下，这样子会不会导致充电电流过大？

第二个问题是：你测试过这个MS621 + BM8563 掉电可以保持RTC多久呢？

谢谢。

**Comment by kekemuyu** [comment]
1.电池是3V的，3.3v经过二极管降到差不多3v左右，不会过充
2.没有实际测试过，电池几十mah，8563耗电是ua级，估计是以年为单位的续航
